// This file is generated by Tools/Reflection/generate_reflection.ps1.
// Do not edit by hand.

#include <Game/GameObjectRegistry.generated.h>

#include <Engine/Objects/3D/Actor/Registry/SceneObjectRegistry.h>

#include <Game/Demo/3D/Actor/DemoCamera/DemoCameraPivot.h>
#include <Game/Demo/3D/Actor/DemoPlayer/DemoPlayer.h>
#include <Game/Enemy/Enemies/HeavyShieldEnemy.h>
#include <Game/Enemy/Enemies/HeavySlime.h>
#include <Game/Player/Player.h>
#include <Game/Player/Base/PlayerBase.h>
#include <Game/Player/Clone/Clone.h>
#include <Game/Enemy/Enemies/ShieldEnemy.h>
#include <Game/Enemy/Enemies/Slime.h>
#include <Game/Player/Sword/Sword.h>
#include <Game/Demo/3D/Actor/DemoPlayer/Weapon/Weapon.h>

namespace CalyxEngine {
	void RegisterGeneratedGameSceneObjects() {
		SceneObjectRegistry::Get().Register(
			"DemoCameraPivot",
			"DemoCameraPivot",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<DemoCameraPivot>);

		SceneObjectRegistry::Get().Register(
			"DemoPlayer",
			"Demo Player",
			ObjectType::GameObject,
			"UI/Tool/cube.dds",
			true,
			false,
			false,
			&CreateSceneObject<DemoPlayer>);

		SceneObjectRegistry::Get().Register(
			"HeavyShieldEnemy",
			"HeavyShieldEnemy",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<HeavyShieldEnemy>);

		SceneObjectRegistry::Get().Register(
			"HeavySlime",
			"HeavySlime",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<HeavySlime>);

		SceneObjectRegistry::Get().Register(
			"Player",
			"Player",
			ObjectType::GameObject,
			"UI/Tool/cube.dds",
			true,
			false,
			false,
			&CreateSceneObject<Player>);

		SceneObjectRegistry::Get().Register(
			"PlayerBase",
			"PlayerBase",
			ObjectType::GameObject,
			"UI/Tool/cube.dds",
			true,
			false,
			false,
			&CreateSceneObject<PlayerBase>);

		SceneObjectRegistry::Get().Register(
			"PlayerClone",
			"PlayerClone",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<PlayerClone>);

		SceneObjectRegistry::Get().Register(
			"ShieldEnemy",
			"ShieldEnemy",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<ShieldEnemy>);

		SceneObjectRegistry::Get().Register(
			"Slime",
			"Slime",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<Slime>);

		SceneObjectRegistry::Get().Register(
			"Sword",
			"Sword",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<Sword>);

		SceneObjectRegistry::Get().Register(
			"Weapon",
			"Weapon",
			ObjectType::GameObject,
			"UI/Tool/AssetPanel/generic.png",
			true,
			false,
			false,
			&CreateSceneObject<Weapon>);
	}
}